name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_call:
    secrets:
      token:
        required: true
        description: "GitHub token for authentication"
    outputs:
      venv-name:
        description: "Name of the virtual environment artifact"
        value: ${{ jobs.setup.outputs.venv-name }}
  workflow_dispatch:

jobs:
  setup:
    name: Setup Environment
    uses: ./.github/workflows/setup-python.yml
    with:
      python-version: "3.11"

  lint:
    name: Lint Check
    needs: [setup]
    uses: ./.github/workflows/lint.yml
    with:
      venv-name: ${{ needs.setup.outputs.venv-name }}
      python-version: "3.11"
    permissions:
      contents: read
      pull-requests: read
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  test:
    name: Run Tests
    needs: [setup]
    uses: ./.github/workflows/test.yml
    with:
      venv-name: ${{ needs.setup.outputs.venv-name }}
      python-version: "3.11"
    permissions:
      contents: read
      checks: write

  release:
    name: Create Release
    # Only run after lint and test pass
    needs: [lint, test]
    # Only run on main branch pushes
    if: |
      github.ref == 'refs/heads/main' &&
      !contains(github.event.head_commit.message, '[skip ci]') &&
      github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Python Semantic Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install python-semantic-release
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          semantic-release version
