name: Lint

on:
  workflow_call: {}  # Allow this workflow to be called by other workflows
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  setup:
    name: Setup Environment
    uses: ./.github/workflows/setup-python.yml
    with:
      python-version: "3.11"

  lint:
    name: Run Linters
    needs: [setup]
    runs-on: ubuntu-latest
    # Skip on release commits
    if: |
      (github.event_name == 'pull_request') ||
      (github.actor != 'github-actions[bot]' &&
       !contains(github.event.head_commit.message, '[skip ci]') &&
       !contains(github.event.head_commit.message, '[ci skip]') &&
       !contains(github.event.head_commit.message, '[no ci]') &&
       !contains(github.event.head_commit.message, 'chore(release)'))

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Poetry
        run: |
          pip install poetry==1.8.5
          poetry config virtualenvs.in-project true

      - name: Run Black
        run: |
          source ${{ needs.setup.outputs.poetry-venv }}/bin/activate
          black --check .

      - name: Check commit messages
        uses: wagoid/commitlint-github-action@v5
        with:
          configFile: commitlint.config.js
          failOnWarnings: true
