name: Lint

on:
  workflow_call:
    inputs:
      artifact-name:
        required: true
        type: string
        description: "Name of the virtual environment artifact"
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  lint:
    name: Run Linters
    runs-on: ubuntu-latest
    # Skip on release commits
    if: |
      (github.event_name == 'pull_request') ||
      (github.actor != 'github-actions[bot]' &&
       !contains(github.event.head_commit.message, '[skip ci]') &&
       !contains(github.event.head_commit.message, '[ci skip]') &&
       !contains(github.event.head_commit.message, '[no ci]') &&
       !contains(github.event.head_commit.message, 'chore(release)'))

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Download virtual environment
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: .venv

      - name: Set environment variables
        run: |
          echo "VIRTUAL_ENV=$PWD/.venv" >> $GITHUB_ENV
          echo "$PWD/.venv/bin" >> $GITHUB_PATH
          chmod -R +x .venv/bin

      - name: Run Black
        run: black --check .

      - name: Check commit messages
        uses: wagoid/commitlint-github-action@v5
        with:
          configFile: commitlint.config.js
          failOnWarnings: true
