name: Lint

on:
  workflow_call:
    inputs:
      venv-name:
        required: true
        type: string
        description: "Name of the virtual environment artifact"
      python-version:
        required: false
        type: string
        default: "3.11"
        description: "Python version to use"
    secrets:
      token:
        required: true
        description: "GitHub token for authentication"

permissions:
  contents: read
  pull-requests: read

jobs:
  lint:
    name: Run Linters
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}

      - name: Download virtual environment
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.venv-name }}
          path: artifact

      - name: Debug downloaded artifact
        run: |
          echo "Artifact directory contents:"
          ls -la artifact/
          echo "Current directory contents:"
          ls -la

      - name: Restore virtual environment
        run: |
          if [ -d "artifact/.venv" ]; then
            cp -r artifact/.venv .
          else
            echo "Contents of artifact directory:"
            ls -la artifact/
            echo "ERROR: No .venv directory found in artifact"
            exit 1
          fi
          cp artifact/poetry.lock .
          cp artifact/pyproject.toml .
          chmod -R +x .venv/bin/

      - name: Run Black
        run: .venv/bin/black --check .

      - name: Check commit messages
        uses: wagoid/commitlint-github-action@v5
        with:
          configFile: commitlint.config.js
          failOnWarnings: true
          token: ${{ secrets.token }}
