name: Release

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      prerelease:
        description: 'Create a prerelease version'
        type: boolean
        required: false
        default: false
      prerelease_token:
        description: 'Token for prerelease version (e.g., alpha, beta)'
        type: string
        required: false
      force:
        description: 'Force version bump (patch, minor, major)'
        type: choice
        options:
          - none
          - patch
          - minor
          - major
        required: false
        default: 'none'

permissions:
  contents: write
  id-token: write

jobs:
  lint:
    name: Lint Check
    uses: ./.github/workflows/lint.yml
    permissions:
      contents: read
      pull-requests: read

  test:
    name: Run Tests
    needs: [lint]
    uses: ./.github/workflows/test.yml
    permissions:
      contents: read
      checks: write

  release:
    name: Create Release
    runs-on: ubuntu-latest
    if: |
      github.ref == 'refs/heads/main' &&
      github.actor != 'github-actions[bot]' &&
      !contains(github.event.head_commit.message, 'chore(release)') &&
      !contains(github.event.head_commit.message, '[skip ci]')
    needs: [lint, test]
    concurrency: release

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install Poetry
        run: |
          pip install poetry==1.8.5
          poetry config virtualenvs.create false

      - name: Install dependencies
        run: poetry install

      - name: Python Semantic Release
        id: release
        uses: python-semantic-release/python-semantic-release@v9.15.0
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          changelog: true
          commit: true
          push: true
          build: true
          tag: true
          vcs_release: true

      - name: Publish to GitHub Release Assets
        uses: python-semantic-release/publish-action@v9.15.0
        if: steps.release.outputs.released == 'true'
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          tag: ${{ steps.release.outputs.tag }}
