name: Release

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      prerelease:
        description: 'Create a prerelease version'
        type: boolean
        required: false
        default: false
      prerelease_token:
        description: 'Token for prerelease version (e.g., alpha, beta)'
        type: string
        required: false
      force:
        description: 'Force version bump (patch, minor, major)'
        type: choice
        options:
          - none
          - patch
          - minor
          - major
        required: false
        default: 'none'

jobs:
  setup:
    name: Setup Environment
    uses: ./.github/workflows/setup-python.yml
    with:
      python-version: "3.11"

  lint:
    name: Lint Check
    needs: [setup]
    uses: ./.github/workflows/lint.yml
    permissions:
      contents: read
      pull-requests: read

  test:
    name: Run Tests
    needs: [setup]
    uses: ./.github/workflows/test.yml
    permissions:
      contents: read
      checks: write

  ci:
    name: Run CI Checks
    uses: ./.github/workflows/ci.yml
    permissions:
      contents: read
      pull-requests: read
      checks: write
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  create_release:
    needs: [ci]

    runs-on: ubuntu-latest
    if: |
      github.ref == 'refs/heads/main' &&
      !contains(github.event.head_commit.message, '[skip ci]') &&
      github.actor != 'github-actions[bot]'
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Python Semantic Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install python-semantic-release
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          semantic-release version
