name: Setup Python Environment

on:
  workflow_call:
    inputs:
      python-version:
        required: false
        type: string
        default: "3.11"
        description: "Python version to use"
    outputs:
      cache-hit:
        description: "Whether there was a cache hit for dependencies"
        value: ${{ jobs.setup.outputs.cache-hit }}
      venv-path:
        description: "Path to the virtual environment"
        value: ${{ jobs.setup.outputs.venv-path }}

jobs:
  setup:
    name: Setup Python
    runs-on: ubuntu-latest
    outputs:
      cache-hit: ${{ steps.cache-deps.outputs.cache-hit }}
      venv-path: ${{ steps.get-venv-path.outputs.path }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}
          cache: "pip"

      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.cache/pypoetry
            .venv
          key: ${{ runner.os }}-python-${{ inputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-python-${{ inputs.python-version }}-
            ${{ runner.os }}-python-

      - name: Install Poetry
        run: |
          pip install poetry==1.8.5
          poetry config virtualenvs.in-project true

      - name: Install dependencies
        run: poetry install

      - name: Get virtual environment path
        id: get-venv-path
        run: |
          echo "path=$PWD/.venv" >> $GITHUB_OUTPUT

      - name: Upload virtual environment
        uses: actions/upload-artifact@v4
        with:
          name: venv
          path: .venv
          retention-days: 1
