name: Setup Python Environment

on:
  workflow_call:
    inputs:
      python-version:
        required: false
        type: string
        default: "3.11"
        description: "Python version to use"
    outputs:
      venv-name:
        description: "Name of the virtual environment artifact"
        value: ${{ jobs.setup.outputs.venv-name }}

jobs:
  setup:
    name: Setup Python
    runs-on: ubuntu-latest
    outputs:
      venv-name: venv-${{ github.run_id }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}
          cache: "pip"

      - name: Install Poetry
        run: |
          pip install poetry==1.8.5
          poetry config virtualenvs.in-project true

      - name: Install dependencies
        run: poetry install

      - name: Debug before copy
        run: |
          echo "Current directory contents:"
          ls -la
          echo "Virtual environment contents:"
          ls -la .venv || echo "No .venv directory"

      - name: Create artifact directory
        run: |
          mkdir -p artifact
          cp poetry.lock artifact/
          cp pyproject.toml artifact/
          cp -r .venv artifact/ || echo "Failed to copy .venv"
          echo "Artifact directory contents:"
          ls -la artifact/
          if [ -d "artifact/.venv" ]; then
            echo "Virtual env in artifact:"
            ls -la artifact/.venv/
          else
            echo "No .venv in artifact directory"
          fi

      - name: Upload virtual environment
        uses: actions/upload-artifact@v4
        with:
          name: venv-${{ github.run_id }}
          path: artifact/
          if-no-files-found: error
