name: Tag Validation

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  validate:
    name: Validate Tag
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.PAT_TOKEN }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}

      - name: Get tag details
        id: tag_details
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "tag_name=${TAG_NAME}" >> $GITHUB_OUTPUT

          # Use git log to get the tagger information from the most recent tag
          TAGGER_NAME=$(git log -1 --format="%an" $TAG_NAME)
          TAGGER_EMAIL=$(git log -1 --format="%ae" $TAG_NAME)
          echo "tagger_name=${TAGGER_NAME}" >> $GITHUB_OUTPUT
          echo "tagger_email=${TAGGER_EMAIL}" >> $GITHUB_OUTPUT

      - name: Validate tag creator
        run: |
          EXPECTED_TAGGER_NAME="github-actions[bot]"
          EXPECTED_TAGGER_EMAIL="41898282+github-actions[bot]@users.noreply.github.com"

          if [ "${{ steps.tag_details.outputs.tagger_name }}" != "$EXPECTED_TAGGER_NAME" ] || \
             [ "${{ steps.tag_details.outputs.tagger_email }}" != "$EXPECTED_TAGGER_EMAIL" ]; then
            echo "Error: Tag ${{ steps.tag_details.outputs.tag_name }} was not created by GitHub Actions"
            echo "Expected: $EXPECTED_TAGGER_NAME <$EXPECTED_TAGGER_EMAIL>"
            echo "Got: ${{ steps.tag_details.outputs.tagger_name }} <${{ steps.tag_details.outputs.tagger_email }}>"
            git push origin :refs/tags/${{ steps.tag_details.outputs.tag_name }}
            exit 1
          fi

      - name: Verify tag format
        run: |
          if ! [[ "${{ steps.tag_details.outputs.tag_name }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+(-([0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*))?(\\+[0-9A-Za-z-]+)?$ ]]; then
            echo "Error: Invalid tag format ${{ steps.tag_details.outputs.tag_name }}"
            git push origin :refs/tags/${{ steps.tag_details.outputs.tag_name }}
            exit 1
          fi
