name: Test

on:
  workflow_call:
    inputs:
      venv-name:
        required: true
        type: string
        description: "Name of the virtual environment artifact"
      python-version:
        required: false
        type: string
        default: "3.11"
        description: "Python version to use"
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  checks: write

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'pull_request') ||
      (github.actor != 'github-actions[bot]' &&
       !contains(github.event.head_commit.message, '[skip ci]') &&
       !contains(github.event.head_commit.message, 'chore(release)'))

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install Poetry
        run: |
          pip install poetry==1.8.5
          poetry config virtualenvs.in-project true

      - name: Download virtual environment
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.venv-name }}
          path: .

      - name: Run tests with coverage
        run: |
          poetry run coverage run -m pytest
          poetry run coverage report -m
