name: Test

on:
  workflow_call:
    inputs:
      venv-name:
        required: true
        type: string
        description: "Name of the virtual environment artifact"
      python-version:
        required: false
        type: string
        default: "3.11"
        description: "Python version to use"

permissions:
  contents: read
  checks: write

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}

      - name: Download virtual environment
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.venv-name }}
          path: artifact
          merge-multiple: true

      - name: Debug downloaded artifact
        run: |
          echo "Artifact directory contents:"
          ls -la artifact/
          echo "Current directory contents:"
          ls -la

      - name: Restore virtual environment
        run: |
          if [ ! -f "artifact/venv.tar.gz" ]; then
            echo "ERROR: venv.tar.gz not found in artifact"
            exit 1
          fi
          tar xzf artifact/venv.tar.gz
          cp artifact/poetry.lock .
          cp artifact/pyproject.toml .
          chmod -R +x .venv/bin/

      - name: Run tests with coverage
        run: |
          .venv/bin/coverage run -m pytest
          .venv/bin/coverage report -m
